import type { NavConfig } from './nav-types';

export const customerNavConfig: NavConfig = {
  brandTitle: 'Merkwacht',
  brandSubtitle: 'Merkbewaking',
  topbarLabel: '',
  storageKey: 'mw-nav-open-customer-v2',
  entries: [
    {
      type: 'leaf',
      id: 'dashboard',
      label: 'Dashboard',
      to: '/app/dashboard',
      icon: 'home',
      matchPrefix: '/app/dashboard',
    },
    {
      type: 'group',
      id: 'mijn-merken',
      label: 'Mijn merken',
      icon: 'marks',
      defaultOpen: true,
      children: [
        {
          type: 'leaf',
          id: 'huidige-merken',
          label: 'Huidige merken',
          to: '/app/bewaakte-merken',
          matchPrefix: '/app/bewaakte-merken',
        },
        {
          type: 'leaf',
          id: 'merken-archief',
          label: 'Merken in archief',
          to: '/app/merken/archief',
          matchPrefix: '/app/merken/archief',
        },
      ],
    },
    {
      type: 'group',
      id: 'matches-groep',
      label: 'Merkbescherming',
      icon: 'matches',
      defaultOpen: false,
      children: [
        {
          type: 'leaf',
          id: 'matches-actief',
          label: 'Actieve matches',
          to: '/app/matches',
          matchPrefix: '/app/matches',
        },
        {
          type: 'leaf',
          id: 'matches-mogelijk',
          label: 'Mogelijke matches',
          to: '/app/matches/mogelijk',
          matchPrefix: '/app/matches/mogelijk',
        },
        {
          type: 'leaf',
          id: 'deadlines',
          label: 'Oppositiedeadlines',
          to: '/app/deadlines',
          matchPrefix: '/app/deadlines',
        },
        {
          type: 'leaf',
          id: 'match-archief',
          label: 'Matcharchief',
          to: '/app/archief',
          matchPrefix: '/app/archief',
        },
      ],
    },
    {
      type: 'group',
      id: 'merkonderzoek-groep',
      label: 'Merkonderzoek',
      icon: 'scoring',
      defaultOpen: false,
      children: [
        {
          type: 'leaf',
          id: 'merkonderzoek-nieuw',
          label: 'Nieuwe aanvraag',
          to: '/app/merkonderzoek/nieuw',
          matchPrefix: '/app/merkonderzoek/nieuw',
        },
        {
          type: 'leaf',
          id: 'merkonderzoek-rapporten',
          label: 'Rapporten',
          to: '/app/merkonderzoek',
          matchPrefix: '/app/merkonderzoek',
        },
      ],
    },
    {
      type: 'leaf',
      id: 'meldingen-inbox',
      label: 'Meldingen',
      to: '/app/meldingen',
      icon: 'notifications',
      matchPrefix: '/app/meldingen',
    },
  ],
  footer: [
    {
      type: 'leaf',
      id: 'org-overview',
      label: 'Bedrijf en gebruikers',
      to: '/app/organisatie',
      icon: 'org',
      matchPrefix: '/app/organisatie',
    },
    {
      type: 'leaf',
      id: 'abonnement',
      label: 'Abonnement en verbruik',
      to: '/app/abonnement',
      icon: 'subscription',
      matchPrefix: '/app/abonnement',
    },
    {
      type: 'leaf',
      id: 'betalingen',
      label: 'Betalingen',
      to: '/app/betalingen',
      matchPrefix: '/app/betalingen',
    },
    {
      type: 'leaf',
      id: 'chat',
      label: 'Merkrechtenchat',
      to: '/app/chat',
      matchPrefix: '/app/chat',
    },
  ],
};

export const platformNavConfig: NavConfig = {
  brandTitle: 'Merkwacht',
  badge: 'Platformbeheer',
  topbarLabel: 'Interne beheeromgeving',
  storageKey: 'mw-nav-open-platform-v2',
  entries: [
    {
      type: 'leaf',
      id: 'overzicht',
      label: 'Platformoverzicht',
      to: '/platform/overzicht',
      icon: 'platform',
      matchPrefix: '/platform/overzicht',
    },
    {
      type: 'group',
      id: 'klanten',
      label: 'Klanten',
      icon: 'customers',
      defaultOpen: true,
      children: [
        {
          type: 'leaf',
          id: 'klanten-lijst',
          label: 'Klanten',
          to: '/platform/klanten',
          matchPrefix: '/platform/klanten',
        },
      ],
    },
    {
      type: 'group',
      id: 'operatie',
      label: 'Operatie',
      icon: 'imports',
      defaultOpen: true,
      children: [
        {
          type: 'leaf',
          id: 'registers',
          label: 'Registers en koppelingen',
          to: '/platform/registers',
          matchPrefix: '/platform/registers',
        },
        {
          type: 'leaf',
          id: 'imports',
          label: 'Imports en verwerking',
          to: '/platform/imports',
          matchPrefix: '/platform/imports',
        },
        {
          type: 'leaf',
          id: 'matches-scoring',
          label: 'Matches en scoring',
          to: '/platform/matches-scoring',
          matchPrefix: '/platform/matches-scoring',
        },
        {
          type: 'leaf',
          id: 'ai-kosten',
          label: 'Koppelingen AI',
          to: '/platform/ai-kosten',
          matchPrefix: '/platform/ai-kosten',
        },
        {
          type: 'leaf',
          id: 'jobs-fouten',
          label: 'Jobs en fouten',
          to: '/platform/jobs-fouten',
          matchPrefix: '/platform/jobs-fouten',
        },
        {
          type: 'leaf',
          id: 'notificaties',
          label: 'Notificaties',
          to: '/platform/notificaties',
          matchPrefix: '/platform/notificaties',
        },
      ],
    },
    {
      type: 'group',
      id: 'systeem',
      label: 'Systeem',
      icon: 'system',
      defaultOpen: false,
      children: [
        {
          type: 'leaf',
          id: 'abonnementen',
          label: 'Abonnementen Merkwacht',
          to: '/platform/abonnementen',
          matchPrefix: '/platform/abonnementen',
        },
        {
          type: 'leaf',
          id: 'prijzen',
          label: 'Prijzen merken',
          to: '/platform/prijzen',
          matchPrefix: '/platform/prijzen',
        },
        {
          type: 'leaf',
          id: 'systeeminstellingen',
          label: 'Systeeminstellingen',
          to: '/platform/systeeminstellingen',
          matchPrefix: '/platform/systeeminstellingen',
        },
        {
          type: 'leaf',
          id: 'auditlog',
          label: 'Auditlog',
          to: '/platform/auditlog',
          matchPrefix: '/platform/auditlog',
        },
      ],
    },
  ],
};
